services:
  namenode:
    image: apache/hadoop:3.4.0
    container_name: namenode
    user: root
    environment:
      - HADOOP_HOME=/opt/hadoop
    ports:
      - "9870:9870"
      - "8020:8020"
    command: ["/bin/bash", "/start-hdfs.sh"]
    volumes:
      - ./hadoop_namenode:/opt/hadoop/data/nameNode
      - ./hadoop_config:/opt/hadoop/etc/hadoop
      - ./shared:/shared
      - ./start-hdfs.sh:/start-hdfs.sh
    networks:
      hdfs_network:
        ipv4_address: 172.20.0.2

  datanode:
    image: apache/hadoop:3.4.0
    container_name: datanode1
    environment:
      - HADOOP_HOME=/opt/hadoop
    command: ["/bin/bash", "/init-datanode.sh"]
    ports:
      - "9864:9864"
    volumes:
      - ./hadoop_datanode1:/opt/hadoop/data/dataNode
      - ./hadoop_config:/opt/hadoop/etc/hadoop
      - ./shared:/shared
      - ./init-datanode.sh:/init-datanode.sh
    networks:
      hdfs_network:
        ipv4_address: 172.20.0.3
  
  resourcemanager:
    image: apache/hadoop:3.4.0
    container_name: resourcemanager
    hostname: resourcemanager
    user: root
    environment:
      - HADOOP_HOME=/opt/hadoop
    ports:
      - "8088:8088"  # ResourceManager Web UI
      - "8030:8030"  # ResourceManager Scheduler
      - "8031:8031"  # ResourceManager Resource Tracker
      - "8032:8032"  # ResourceManager Application Manager
    command: ["/bin/bash", "/start-yarn.sh"]
    volumes:
      - ./hadoop_config:/opt/hadoop/etc/hadoop
      - ./shared:/shared
      - ./start-yarn.sh:/start-yarn.sh
    networks:
      hdfs_network:
        ipv4_address: 172.20.0.4
    depends_on:
      - namenode


  nodemanager:
    image: apache/hadoop:3.4.0
    container_name: nodemanager1
    hostname: nodemanager1
    environment:
      - HADOOP_HOME=/opt/hadoop
    ports:
      - "8042:8042"  # NodeManager Web UI
    command: ["/bin/bash", "/start-nodemanager.sh"]
    volumes:
      - ./hadoop_nodemanager1:/opt/hadoop/data/nodeManager
      - ./hadoop_config:/opt/hadoop/etc/hadoop
      - ./shared:/shared
      - ./start-nodemanager.sh:/start-nodemanager.sh
    networks:
      hdfs_network:
        ipv4_address: 172.20.0.5
    depends_on:
      - resourcemanager

networks:
  hdfs_network:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
